### ISSUE TITLE
Linking Icon to page

### ISSUE THREAD

**Issue by rcortez1775** [rcortez1775/broadwaypc#1]
Hey there,

I want to render a new page when an icon is selected. I  created routes and  added an href tag to each icon(button). When an icon was selected, only the home icon would be highlighted regardless of what icon was selected. @basketofsoftkittens 

![Screen Shot 2019-04-07 at 1 31 09 PM](https://user-images.githubusercontent.com/38049358/55689452-6db38400-5939-11e9-9c55-374318c12680.png)

**Comment by rcortez1775** [comment]
I found this. Do you feel this is what I am trying to do? 

https://material-ui.com/demos/buttons/#third-party-routing-library

**Comment by basketofsoftkittens** [comment]
couple questions:
1) Does it go to the page you expect it to when you click on any of the icons?
2) if it does, is the problem that the correct button on the navbar isnt selected based on the url?

**Comment by rcortez1775** [comment]
@basketofsoftkittens 

1.) I don't think it routes to a new page at all. So the issue could be with connecting the routes to different views.

2.) It does not. :(

**Comment by basketofsoftkittens** [comment]
I looked at the docs and it appears you are adding a `href` prop to that component. which it doesnt support. https://material-ui.com/api/bottom-navigation-action/

what you would have to do is in your `handleChange` method, you would have redirect the user to the appropriate route based on which button they selected. https://tylermcginnis.com/react-router-programmatically-navigate/
